'use strict';
// Generated by CoffeeScript 1.9.1

const assign = require('./lodash/assign');

const XMLBuilder = require('./XMLBuilder');

module.exports.create = function(name, xmldec, doctype, options) {
  options = assign({}, xmldec, doctype, options);
  return new XMLBuilder(name, options).root();
};
