'use strict';
// Generated by CoffeeScript 1.9.1
(function() {
  let XMLDTDElement; let create;

  create = require('lodash/create');

  module.exports = XMLDTDElement = (function() {
    function XMLDTDElement(parent, name, value) {
      this.stringify = parent.stringify;
      if ((name === null || name === undefined)) {
        throw new Error('Missing DTD element name');
      }
      if (!value) {
        value = '(#PCDATA)';
      }
      if (Array.isArray(value)) {
        value = '(' + value.join(',') + ')';
      }
      this.name = this.stringify.eleName(name);
      this.value = this.stringify.dtdElementValue(value);
    }

    XMLDTDElement.prototype.toString = function(options, level) {
      let indent; let newline; let offset; let pretty; let r; let ref; let ref1; let ref2; let space;
      pretty = ((options !== null || options !== undefined) ? options.pretty : undefined) || false;
      indent = (ref = (options !== null || options !== undefined) ? options.indent : undefined) != null ? ref : '  ';
      offset = (ref1 = (options !== null || options !== undefined) ? options.offset : undefined) != null ? ref1 : 0;
      newline = (ref2 = (options !== null || options !== undefined) ? options.newline : undefined) != null ? ref2 : '\n';
      level || (level = 0);
      space = new Array(level + offset + 1).join(indent);
      r = '';
      if (pretty) {
        r += space;
      }
      r += '<!ELEMENT ' + this.name + ' ' + this.value + '>';
      if (pretty) {
        r += newline;
      }
      return r;
    };

    return XMLDTDElement;

  })();

}).call(this);
