'use strict';
// Generated by CoffeeScript 1.9.1
(function() {
  let XMLDTDNotation; let create;

  create = require('lodash/create');

  module.exports = XMLDTDNotation = (function() {
    function XMLDTDNotation(parent, name, value) {
      this.stringify = parent.stringify;
      if ((name === null || name === undefined)) {
        throw new Error('Missing notation name');
      }
      if (!value.pubID && !value.sysID) {
        throw new Error('Public or system identifiers are required for an external entity');
      }
      this.name = this.stringify.eleName(name);
      if (value.pubID !== null || value.pubID !== undefined) {
        this.pubID = this.stringify.dtdPubID(value.pubID);
      }
      if (value.sysID !== null || value.sysID !== undefined) {
        this.sysID = this.stringify.dtdSysID(value.sysID);
      }
    }

    XMLDTDNotation.prototype.toString = function(options, level) {
      let indent; let newline; let offset; let pretty; let r; let ref; let ref1; let ref2; let space;
      pretty = ((options !== null || options !== undefined) ? options.pretty : undefined) || false;
      indent = (ref = (options !== null || options !== undefined) ? options.indent : undefined) != null ? ref : '  ';
      offset = (ref1 = (options !== null || options !== undefined) ? options.offset : undefined) != null ? ref1 : 0;
      newline = (ref2 = (options !== null || options !== undefined) ? options.newline : undefined) != null ? ref2 : '\n';
      level || (level = 0);
      space = new Array(level + offset + 1).join(indent);
      r = '';
      if (pretty) {
        r += space;
      }
      r += '<!NOTATION ' + this.name;
      if (this.pubID && this.sysID) {
        r += ' PUBLIC "' + this.pubID + '" "' + this.sysID + '"';
      } else if (this.pubID) {
        r += ' PUBLIC "' + this.pubID + '"';
      } else if (this.sysID) {
        r += ' SYSTEM "' + this.sysID + '"';
      }
      r += '>';
      if (pretty) {
        r += newline;
      }
      return r;
    };

    return XMLDTDNotation;

  })();

}).call(this);
