language: node_js
node_js:
  - "6"
  - "6.1"
  - "6.2"
  - "6.3"
  - "6.4"
  - "6.5"

before_install:
  - rm ./package.json
  - mv ./package-linux.json package.json
  - mv ./data/xdata-base.json data/xdata.json

cache:
  directories:
    - node_modules
