language: node_js
node_js:
  - stable
  - "5"
  - "5.1"
  - "4"
  - "4.2"
  - "4.1"
  - "4.0"

before_install:
  - rm ./package.json
  - mv ./package-linux.json package.json

cache:
  directories:
    - node_modules
