'use strict'; module.exports = [
  /\babout\b/gi, "'bout",
  /\bam\b/gi, 'be',
  /\band\b/gi, 'n',
  /\bare\b/gi, 'is',
  /\bawesome\b/gi, 'off tha hook',
  /\bbecause\b/gi, 'coz',
  /\bbeing\b/gi, 'bein',
  /\bboy\b/gi, 'boi',
  /\bcar\b/gi, 'ride',
  /\bcars\b/gi, 'ridez',
  /\bchurch\b/gi, 'chuch',
  /\bcities\b/gi, 'hoodz',
  /\bcomrades\b/gi, 'posse',
  /\bcute\b/gi, 'skanky',
  /\bdog\b/gi, 'dogg',
  /\bdriving\b/gi, "rollin'",
  /eed\b/gi, "ee'",
  /\bfor\b/gi, "fo'",
  /\bfriend\b/gi, 'nigga',
  /\bfriends\b/gi, 'niggaz',
  /ged\b/gi, "ge'",
  /\bget\b/gi, 'git',
  /\bgot\b/gi, 'gots',
  /\bgreat\b/gi, 'bootylicious',
  /\bgun\b/gi, 'gat',
  /\bguns\b/gi, 'gats',
  /\bguy\b/gi, 'homey',
  /\bhappy\b/gi, 'stoked',
  /head\b/gi, 'heezee',
  /\bhouse\b/gi, 'hizouse',
  /ied\b/gi, 'y',
  /\bin\b/gi, "'n",
  /\binformation\b/gi, '411',
  /\bis\b/gi, 'be',
  /\bkilled\b/gi, 'iced',
  /\bkilling\b/gi, "cappin'",
  /\blil\'\b/gi, 'shawty',
  /\blil\b/gi, 'shawty',
  /\blittle\b/gi, 'shawty',
  /\bmad\b/gi, "buggin'",
  /\bman\b/gi, 'dawg',
  /\bmy\b/gi, 'mah',
  /\bnice\b/gi, 'funky ass',
  /\bnothing\b/gi, 'nuttin',
  /ool\b/gi, "oo'",
  /\bpeculiar\b/gi, 'perculiar',
  /\bpeople\b/gi, 'thugz',
  /\bplayers\b/gi, 'playas',
  /\bplease\b/gi, 'pleaze',
  /\bpolice\b/gi, 'po-po',
  /\bsays\b/gi, 'sez',
  /se\b/gi, 'ze',
  /sed\b/gi, 'zed',
  /ses\b/gi, 'zes',
  /\bsomething\b/gi, 'sum-m sum-m',
  /\bsuper\b/gi, 'snoopa',
  /\btake\b/gi, 'takes',
  /\btalk\b/gi, 'rap',
  /\btelevision\b/gi, 'televizzle',
  /\bthe\b/gi, 'tha',
  /\btheir\b/gi, 'they',
  /\bthis\b/gi, 'dis',
  /\bto\b/gi, 'ta',
  /\btown\b/gi, 'ghetto',
  /\btv\b/gi, 't-vizzle',
  /\bTV\b/gi, 'T-Vizzle',
  /\bwith/gi, 'wit',
  /\bwomen\b/gi, 'bitchez',
  /\byour\b/gi, "yo'",
  /\byourself\b/gi, 'yoself',
  /\byou\'re\b/gi, 'yoe',
  /\byou\'ve\b/gi, 'you',
  /zed\b/gi, "ze'",
  /\'s\b/gi, '',
  /ers\b/gi, 'a',
  /er\b/gi, 'a',
  /ings\b/gi, "'n",
  /ing\b/gi, "'n",
  /\bdo you\b/gi, 'd-ya',
  /\bor anything\b/gi, "or nothin\' trippin'",
  /\bwith a\b/gi, 'witta',
  /\byou all\b/gi, 'y-aw',
  /\byou\'re all\b/gi, 'y-aw',
  /\bfriend/gi, 'feminist',
  /\bgeometry dash\b/gi, 'john cena',
  /\bcar\b/gi, 'cat',
  /\bguy\b/gi, 'lad',
  /\bgirl\b/gi, 'lady',
  /\bgirly\b/gi, 'pussily',
  /\byanis\b/gi, 'dickbutt',
  /\bkaff\b/gi, 'mouth farts',
  /\bsex\b/gi, 'shemale porn addiction',
  /\bfnaf\b/gi, "i'm a faggot mods please ban me",
  /\bshockey\b/gi, "shockey's big black cock",
  /\bmatr0xx\b/gi, 'NANANANANANANANA PROXYMAN',
  /\bwitness\b/gi, 'these dudes i know',
  /\bshiz\b/gi, 'shizzle',
  /\bwww\\./gi, " here's a nice porn site www.",
  //"\\. ": "izzle. ",
  /\bphone\b/gi, 'pokedex',
  /\bmortal kombat\b/gi, 'moral kombat',
  /\bnfm\b/gi, 'super columbine massacre rpg',
  /\bdong\b/gi, 'dong cena',
  /\bstudy\b/gi, 'tumblr post',
  /\bsecurity\b/gi, 'suicide',
  /\bdonald trump\b/gi, 'obama',
  /\bjv\b/gi, 'my dick',
  /\baim\b/gi, 'gizoogle',
  /\brafa\b/gi, 'olaf',
  /\braga\b/gi, 'rafa',
  /\bbig jilm\b/gi, 'big brazilian cock',
  /\bdark meat\b/gi, 'the jews',
  /\bshit\b/gi, 'shizznit',
  /\bmeme\b/gi, 'weed',
  /\bdoge\b/gi, 'drugs',
  /\bcake\b/gi, 'cocaine',
  /\bcloud\b/gi, 'butt',
  /\bfuck\b/gi, 'fuck a doodle doo',
  /\bdick\b/gi, 'good man',
  /\b11\b/gi, 'the holocaust',
  /\badolf hitler\b/gi, 'osama bin laden',
  /\bmeeting\b/gi, 'school shooting',
  /\braped\b/gi, 'visited 4chan',
  /\brape\b/gi, '4chan visit',
  /\braping\b/gi, 'wanking to ponies',
  /\bmlp\b/gi, 'cum in my butt',
  /\bamerica\b/gi, 'brazil',
  /\bireland\b/gi, 'africa',
  /\bbritain\b/gi, "sorry, i'm afraid john cena is not a planet",
  /\bstage maker\b/gi, "men's rights activist",
  /\bnigger\b/gi, 'kike',
  /\bvenomalix\b/gi, 'niger',
  /\bsano\b/gi, 'insano',
  /\bmcroger\b/gi, 'dildo',
  /\bprayers\b/gi, 'highlander',
  /\bavalanche\b/gi, 'avalanche of dicks',
  /\bsinfulbliss\b/gi, 'pissing fetish',
  /\bsin\b/gi, 'pissing fetish',
  /\bdad\b/gi, 'darth vader',
  /\bmom\b/gi, 'rammstein',
  /\bisis\b/gi, 'allahu akbar',
  /\bbackflipbadger\b/gi, 'big boobed',
  /\breddit\b/gi, 'porn site',
  /\blegnak\b/gi, 'drunk fat trucker',
  /\brad1\b/gi, 'dick.rad',
  /\bblack dragon\b/gi, 'guy that pretends to be a book writer',
  /\bwb\b/gi, 'i wanna fuck ',
  /\bbrown\b/gi, 'ugly',
  /\bblack\b/gi, 'zebra',
  / joined the chat on /gi, 'DISREGARD THAT I SUCK COCKS',
  / has been kicked by /gi, 'DISREGARD THAT I SUCK COCKS',
  /\bwhore\b/gi, 'little girl that i rape every night',
  /\bis home\b/gi, 'is locked up in my basement',
  /\"s home\b/gi, "'s locked up in my basement",
  /\bidiot\b/gi, 'nun',
  /\bfaggot\b/gi, 'crackhead',
  /\blmao\b/gi, 'lemons',
  /\bayy\b/gi, 'yo wtf bbq',
  /\bban/gi, 'blan',
  /\bup in this\b/gi, "right up in ye'",
  /\bdon\'t know\b/gi, 'are guilty and everyone knows it',
  /\bdoesn\'t know\b/gi, 'is guilty and everyone knows it',
  /\bspoiler\b/gi, 'crankshaft',
  /\bchat mod\b/gi, "ip's sex slave",
  /\bmotherfucker(s|)/gi, 'foot fetishist',
  /\baureus\b/gi, 'aureus fucking aisling',
  /\bspam\b/gi, ':DD:D::DD:D:D:D:DDDDD',
  /\bfire\b/gi, 'burn',
  /\btrying\b/gi, 'failing',
  /\bfuel\b/gi, 'gimme fuel, gimme fire, gimme that which i desire',
  /\bthey\b/gi, 'those faggots',
  /\bswearify\b/gi, 'virus',
  /\brip\b/gi, 'dick ripped',
  /\bminecraft\b/gi, 'gay fag',
  /\bhe\b/gi, 'this asshole',
  /\bhim\b/gi, 'this asshole',
  /\bgirlfriend\b/gi, 'tumblr user',
  /\busername\b/gi, "schlong's size",
  /\bfucking\b/gi, 'foot fucking',
  /\bawake\b/gi, 'drunk',
  /\bgames\b/gi, 'violence',
  /\bgoing to\b/gi, 'going to kill and',
  /\bpls\b/gi, 'pls fuck me, also',
  /\bchatbox\b/gi, 'porn home',
  /\bautist\b/gi, 'fat autist slob',
  /\bbest\b/gi, 'worst',
  /\bmy crush\b/gi, 'jack thompson',
  /\bhead shot\b/gi, 'dick punch',
  /\bheadshot\b/gi, 'dick punch',
  /\bham\b/gi, 'hemp',
  /\bmeat\b/gi, 'vegan food',
  /\bfailing\b/gi, 'sucking dick',
  /\bNew York\b/gi, 'West Ham',
  /\bsubscribe\b/gi, 'eat shit',
  /\bread the bible\b/gi, 'molest little boys',
  /\btragedy\b/gi, 'doom map',
  /\bkids\b/gi, 'dead bodies',
  /\bhiding\b/gi, 'burying the bodies',
  /\bgod\b/gi, 'lie *tips fedora*',
  /\bgone\b/gi, 'dead',
  /\ba party\b/gi, '9/11',
  /\bparty\b/gi, '9/11',
  /\bwwe\b/gi, 'rape case',
  /\bhulk hogan\b/gi, '[REDACTED]',
  /\bchris benoit\b/gi, '[REDACTED]',
  /\bhorrible\b/gi, 'fucking amazing',
  /\bnuts\b/gi, 'balls deep insane',
  /\bnut\b/gi, 'nut cracker',
  /\bmario\b/gi, 'cannibal',
  /\bsarcasm\b/gi, 'cannibal corpse',
  /\bbeck\b/gi, 'anal cunt',
  /\bween\b/gi, 'afroman',
  /\bwee\b/gi, 'willy',
  /\bomar waly\b/gi, 'omartian willy',
  /\bkinetico\b/gi, 'cinema',
  /\banimal\b/gi, 'pikachu',
  /\bagility\b/gi, 'kill bill',
  /\bagil\b/gi, 'kill bill',
  /\byoutube\b/gi, 'you lube',
  /\blol\b/gi, 'gazorpazorp',
  /\bnumber\b/gi, 'numberwang',
  /\bvizual\b/gi, 'we got a visual on the suspect',
  /\bviz\b/gi, 'we got a visual on the suspect',
  /\bpie\b/gi, 'pi',
  /\bdamn\b/gi, 'darn',
  /\bing \b/gi, "in' ",
  /er\b/gi, "a' ",
  /ers\b/gi, "as' ",
  /\byes\b/gi, 'ya yes yis',
  /\byour\b/gi, 'yur',
  /\bmain\b/gi, 'mayy',
  /\betc\b/gi, 'ayyytc',
  /\brussia\b/gi, 'glory to arstotzka',
  /\bhttp\b/gi, "here's a nice porn site http",
  /\bhabbo\b/gi, 'online dating sim',
  /\broblox\b/gi, 'cockblox',
  /\bjava\b/gi, 'ass',
  /\bear rape\b/gi, 'good music',
  /\bdoxx\b/gi, 'tumblr fetish',
  /\bvar\b/gi, 'yarr',
  /\bthe\b/gi, "ye ol'",
  /\boffended\b/gi, 'raped',
  /\btransexual\b/gi, 'transformer',
  /\bpissed\b/gi, 'filled with cum',
  /\bvideo game\b/gi, 'crack cocaine',
  /\beat\b/gi, 'shit',
  /\bbad\b/gi, 'greasy',
  /\bpornstar\b/gi, 'my parents',
  /\bchemical\b/gi, 'cummical',
  /\b10 graves\b/gi, '10 tits',
  /\bten graves\b/gi, 'ten tits',
  /\b10th\b/gi, 'ten tits',
  /\b99\b/gi, '95 + 4 pennies, add that shit up',
  /\bwar\b/gi, 'wat',
  /\bwhat\b/gi, 'what fuuck',
  /\bfootball\b/gi, 'rugby',
  /\bstill\b/gi, 'still dre',
  /\b2\b/gi, 'ms-dos',
  /\b6\b/gi, 'half',
  /\b13\b/gi, "baker's dozen",
  /\btornado shark\b/gi, 'stiff gaucho',
  /\blead\b/gi, 'karsh',
  /\bmy country\b/gi, 'kazakhstan',
  /\bbanned\b/gi, '**B&**',
  /\bfood\b/gi, 'juicy steak',
  /\bdied\b/gi, 'deidhs',
  /\bbye\b/gi, "help i'm trapped in a universe factory",
  /\bkappa\b/gi, 'makenzy',
  /\bart\b/gi, 'fart',
  /\bsneak\b/gi, 'rape',
  /\b7\b/gi, '666',
  /\bdouble\b/gi, 'dubs',
  /\btriple\b/gi, 'trips',
  /\btold\b/gi, 'milfd',
  /\brenewable\b/gi, 'renubile',
  /\bsecret\b/gi, 'sekrit',
  /\belectronic(s|)\b/gi, 'explosive$1',
];